/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BatchesRouteImport } from './routes/batches'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IncidentsRouteImport } from './routes/incidents'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SupplyChainRouteImport } from './routes/supply-chain'
import { Route as VerificationRouteImport } from './routes/verification'
import { Route as BatchesIndexRouteImport } from './routes/batches.index'
import { Route as BatchesBatchIdRouteImport } from './routes/batches.$batchId'
import { Route as IncidentsIndexRouteImport } from './routes/incidents.index'
import { Route as IncidentsIncidentIdRouteImport } from './routes/incidents.$incidentId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BatchesRoute = BatchesRouteImport.update({
  id: '/batches',
  path: '/batches',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IncidentsRoute = IncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SupplyChainRoute = SupplyChainRouteImport.update({
  id: '/supply-chain',
  path: '/supply-chain',
  getParentRoute: () => rootRouteImport,
} as any)
const VerificationRoute = VerificationRouteImport.update({
  id: '/verification',
  path: '/verification',
  getParentRoute: () => rootRouteImport,
} as any)
const BatchesIndexRoute = BatchesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BatchesRoute,
} as any)
const BatchesBatchIdRoute = BatchesBatchIdRouteImport.update({
  id: '/$batchId',
  path: '/$batchId',
  getParentRoute: () => BatchesRoute,
} as any)
const IncidentsIndexRoute = IncidentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => IncidentsRoute,
} as any)
const IncidentsIncidentIdRoute = IncidentsIncidentIdRouteImport.update({
  id: '/$incidentId',
  path: '/$incidentId',
  getParentRoute: () => IncidentsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/batches': typeof BatchesRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/incidents': typeof IncidentsRouteWithChildren
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/supply-chain': typeof SupplyChainRoute
  '/verification': typeof VerificationRoute
  '/batches/$batchId': typeof BatchesBatchIdRoute
  '/incidents/$incidentId': typeof IncidentsIncidentIdRoute
  '/batches/': typeof BatchesIndexRoute
  '/incidents/': typeof IncidentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/supply-chain': typeof SupplyChainRoute
  '/verification': typeof VerificationRoute
  '/batches/$batchId': typeof BatchesBatchIdRoute
  '/incidents/$incidentId': typeof IncidentsIncidentIdRoute
  '/batches': typeof BatchesIndexRoute
  '/incidents': typeof IncidentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/batches': typeof BatchesRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/incidents': typeof IncidentsRouteWithChildren
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/supply-chain': typeof SupplyChainRoute
  '/verification': typeof VerificationRoute
  '/batches/$batchId': typeof BatchesBatchIdRoute
  '/incidents/$incidentId': typeof IncidentsIncidentIdRoute
  '/batches/': typeof BatchesIndexRoute
  '/incidents/': typeof IncidentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/batches'
    | '/dashboard'
    | '/incidents'
    | '/login'
    | '/settings'
    | '/supply-chain'
    | '/verification'
    | '/batches/$batchId'
    | '/incidents/$incidentId'
    | '/batches/'
    | '/incidents/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/settings'
    | '/supply-chain'
    | '/verification'
    | '/batches/$batchId'
    | '/incidents/$incidentId'
    | '/batches'
    | '/incidents'
  id:
    | '__root__'
    | '/'
    | '/batches'
    | '/dashboard'
    | '/incidents'
    | '/login'
    | '/settings'
    | '/supply-chain'
    | '/verification'
    | '/batches/$batchId'
    | '/incidents/$incidentId'
    | '/batches/'
    | '/incidents/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BatchesRoute: typeof BatchesRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  IncidentsRoute: typeof IncidentsRouteWithChildren
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRoute
  SupplyChainRoute: typeof SupplyChainRoute
  VerificationRoute: typeof VerificationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/batches': {
      id: '/batches'
      path: '/batches'
      fullPath: '/batches'
      preLoaderRoute: typeof BatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incidents': {
      id: '/incidents'
      path: '/incidents'
      fullPath: '/incidents'
      preLoaderRoute: typeof IncidentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supply-chain': {
      id: '/supply-chain'
      path: '/supply-chain'
      fullPath: '/supply-chain'
      preLoaderRoute: typeof SupplyChainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verification': {
      id: '/verification'
      path: '/verification'
      fullPath: '/verification'
      preLoaderRoute: typeof VerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/batches/': {
      id: '/batches/'
      path: '/'
      fullPath: '/batches/'
      preLoaderRoute: typeof BatchesIndexRouteImport
      parentRoute: typeof BatchesRoute
    }
    '/batches/$batchId': {
      id: '/batches/$batchId'
      path: '/$batchId'
      fullPath: '/batches/$batchId'
      preLoaderRoute: typeof BatchesBatchIdRouteImport
      parentRoute: typeof BatchesRoute
    }
    '/incidents/': {
      id: '/incidents/'
      path: '/'
      fullPath: '/incidents/'
      preLoaderRoute: typeof IncidentsIndexRouteImport
      parentRoute: typeof IncidentsRoute
    }
    '/incidents/$incidentId': {
      id: '/incidents/$incidentId'
      path: '/$incidentId'
      fullPath: '/incidents/$incidentId'
      preLoaderRoute: typeof IncidentsIncidentIdRouteImport
      parentRoute: typeof IncidentsRoute
    }
  }
}

interface BatchesRouteChildren {
  BatchesBatchIdRoute: typeof BatchesBatchIdRoute
  BatchesIndexRoute: typeof BatchesIndexRoute
}

const BatchesRouteChildren: BatchesRouteChildren = {
  BatchesBatchIdRoute: BatchesBatchIdRoute,
  BatchesIndexRoute: BatchesIndexRoute,
}

const BatchesRouteWithChildren =
  BatchesRoute._addFileChildren(BatchesRouteChildren)

interface IncidentsRouteChildren {
  IncidentsIncidentIdRoute: typeof IncidentsIncidentIdRoute
  IncidentsIndexRoute: typeof IncidentsIndexRoute
}

const IncidentsRouteChildren: IncidentsRouteChildren = {
  IncidentsIncidentIdRoute: IncidentsIncidentIdRoute,
  IncidentsIndexRoute: IncidentsIndexRoute,
}

const IncidentsRouteWithChildren = IncidentsRoute._addFileChildren(
  IncidentsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BatchesRoute: BatchesRouteWithChildren,
  DashboardRoute: DashboardRoute,
  IncidentsRoute: IncidentsRouteWithChildren,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRoute,
  SupplyChainRoute: SupplyChainRoute,
  VerificationRoute: VerificationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
